// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Activity is the predicate function for activity builders.
type Activity func(*sql.Selector)

// Friendship is the predicate function for friendship builders.
type Friendship func(*sql.Selector)

// Hex is the predicate function for hex builders.
type Hex func(*sql.Selector)

// HexInfluence is the predicate function for hexinfluence builders.
type HexInfluence func(*sql.Selector)

// HexLeaderboard is the predicate function for hexleaderboard builders.
type HexLeaderboard func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
