// Code generated by ent, DO NOT EDIT.

package hex

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the hex type in the database.
	Label = "hex"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHexOwner holds the string denoting the hex_owner field in the database.
	FieldHexOwner = "hex_owner"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// Table holds the table name of the hex in the database.
	Table = "hexes"
)

// Columns holds all SQL columns for hex fields.
var Columns = []string{
	FieldID,
	FieldHexOwner,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldIsActive,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Hex queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHexOwner orders the results by the hex_owner field.
func ByHexOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHexOwner, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}
