linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gocritic
    - gosimple

gofmt:
  simplify: true

run:
  timeout: 2m

issues:
  exclude-use-default: false