version: 1.64.8

run:
  timeout: 2m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gocritic
    - gosimple

linters-settings:
  gofmt:
    simplify: true

issues:
  exclude-use-default: false
