// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"stride-wars-app/ent/hex"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Hex is the model entity for the Hex schema.
type Hex struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// HexOwner holds the value of the "hex_owner" field.
	HexOwner int64 `json:"hex_owner,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive     bool `json:"is_active,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Hex) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case hex.FieldIsActive:
			values[i] = new(sql.NullBool)
		case hex.FieldID, hex.FieldHexOwner:
			values[i] = new(sql.NullInt64)
		case hex.FieldCreatedAt, hex.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Hex fields.
func (h *Hex) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case hex.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			h.ID = int(value.Int64)
		case hex.FieldHexOwner:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hex_owner", values[i])
			} else if value.Valid {
				h.HexOwner = value.Int64
			}
		case hex.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				h.CreatedAt = value.Time
			}
		case hex.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				h.UpdatedAt = value.Time
			}
		case hex.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				h.IsActive = value.Bool
			}
		default:
			h.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Hex.
// This includes values selected through modifiers, order, etc.
func (h *Hex) Value(name string) (ent.Value, error) {
	return h.selectValues.Get(name)
}

// Update returns a builder for updating this Hex.
// Note that you need to call Hex.Unwrap() before calling this method if this Hex
// was returned from a transaction, and the transaction was committed or rolled back.
func (h *Hex) Update() *HexUpdateOne {
	return NewHexClient(h.config).UpdateOne(h)
}

// Unwrap unwraps the Hex entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (h *Hex) Unwrap() *Hex {
	_tx, ok := h.config.driver.(*txDriver)
	if !ok {
		panic("ent: Hex is not a transactional entity")
	}
	h.config.driver = _tx.drv
	return h
}

// String implements the fmt.Stringer.
func (h *Hex) String() string {
	var builder strings.Builder
	builder.WriteString("Hex(")
	builder.WriteString(fmt.Sprintf("id=%v, ", h.ID))
	builder.WriteString("hex_owner=")
	builder.WriteString(fmt.Sprintf("%v", h.HexOwner))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(h.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(h.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", h.IsActive))
	builder.WriteByte(')')
	return builder.String()
}

// Hexes is a parsable slice of Hex.
type Hexes []*Hex
