// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"stride-wars-app/ent/hex"
	"stride-wars-app/ent/hexinfluence"
	"stride-wars-app/ent/hexleaderboard"
	"stride-wars-app/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HexUpdate is the builder for updating Hex entities.
type HexUpdate struct {
	config
	hooks    []Hook
	mutation *HexMutation
}

// Where appends a list predicates to the HexUpdate builder.
func (hu *HexUpdate) Where(ps ...predicate.Hex) *HexUpdate {
	hu.mutation.Where(ps...)
	return hu
}

// AddHexinfluenceIDs adds the "hexinfluences" edge to the HexInfluence entity by IDs.
func (hu *HexUpdate) AddHexinfluenceIDs(ids ...int) *HexUpdate {
	hu.mutation.AddHexinfluenceIDs(ids...)
	return hu
}

// AddHexinfluences adds the "hexinfluences" edges to the HexInfluence entity.
func (hu *HexUpdate) AddHexinfluences(h ...*HexInfluence) *HexUpdate {
	ids := make([]int, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return hu.AddHexinfluenceIDs(ids...)
}

// AddHexleaderboardIDs adds the "hexleaderboards" edge to the HexLeaderboard entity by IDs.
func (hu *HexUpdate) AddHexleaderboardIDs(ids ...int) *HexUpdate {
	hu.mutation.AddHexleaderboardIDs(ids...)
	return hu
}

// AddHexleaderboards adds the "hexleaderboards" edges to the HexLeaderboard entity.
func (hu *HexUpdate) AddHexleaderboards(h ...*HexLeaderboard) *HexUpdate {
	ids := make([]int, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return hu.AddHexleaderboardIDs(ids...)
}

// Mutation returns the HexMutation object of the builder.
func (hu *HexUpdate) Mutation() *HexMutation {
	return hu.mutation
}

// ClearHexinfluences clears all "hexinfluences" edges to the HexInfluence entity.
func (hu *HexUpdate) ClearHexinfluences() *HexUpdate {
	hu.mutation.ClearHexinfluences()
	return hu
}

// RemoveHexinfluenceIDs removes the "hexinfluences" edge to HexInfluence entities by IDs.
func (hu *HexUpdate) RemoveHexinfluenceIDs(ids ...int) *HexUpdate {
	hu.mutation.RemoveHexinfluenceIDs(ids...)
	return hu
}

// RemoveHexinfluences removes "hexinfluences" edges to HexInfluence entities.
func (hu *HexUpdate) RemoveHexinfluences(h ...*HexInfluence) *HexUpdate {
	ids := make([]int, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return hu.RemoveHexinfluenceIDs(ids...)
}

// ClearHexleaderboards clears all "hexleaderboards" edges to the HexLeaderboard entity.
func (hu *HexUpdate) ClearHexleaderboards() *HexUpdate {
	hu.mutation.ClearHexleaderboards()
	return hu
}

// RemoveHexleaderboardIDs removes the "hexleaderboards" edge to HexLeaderboard entities by IDs.
func (hu *HexUpdate) RemoveHexleaderboardIDs(ids ...int) *HexUpdate {
	hu.mutation.RemoveHexleaderboardIDs(ids...)
	return hu
}

// RemoveHexleaderboards removes "hexleaderboards" edges to HexLeaderboard entities.
func (hu *HexUpdate) RemoveHexleaderboards(h ...*HexLeaderboard) *HexUpdate {
	ids := make([]int, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return hu.RemoveHexleaderboardIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (hu *HexUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, hu.sqlSave, hu.mutation, hu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (hu *HexUpdate) SaveX(ctx context.Context) int {
	affected, err := hu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (hu *HexUpdate) Exec(ctx context.Context) error {
	_, err := hu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hu *HexUpdate) ExecX(ctx context.Context) {
	if err := hu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (hu *HexUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(hex.Table, hex.Columns, sqlgraph.NewFieldSpec(hex.FieldID, field.TypeString))
	if ps := hu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if hu.mutation.HexinfluencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hex.HexinfluencesTable,
			Columns: []string{hex.HexinfluencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hexinfluence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := hu.mutation.RemovedHexinfluencesIDs(); len(nodes) > 0 && !hu.mutation.HexinfluencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hex.HexinfluencesTable,
			Columns: []string{hex.HexinfluencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hexinfluence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := hu.mutation.HexinfluencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hex.HexinfluencesTable,
			Columns: []string{hex.HexinfluencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hexinfluence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if hu.mutation.HexleaderboardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hex.HexleaderboardsTable,
			Columns: []string{hex.HexleaderboardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hexleaderboard.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := hu.mutation.RemovedHexleaderboardsIDs(); len(nodes) > 0 && !hu.mutation.HexleaderboardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hex.HexleaderboardsTable,
			Columns: []string{hex.HexleaderboardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hexleaderboard.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := hu.mutation.HexleaderboardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hex.HexleaderboardsTable,
			Columns: []string{hex.HexleaderboardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hexleaderboard.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, hu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hex.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	hu.mutation.done = true
	return n, nil
}

// HexUpdateOne is the builder for updating a single Hex entity.
type HexUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HexMutation
}

// AddHexinfluenceIDs adds the "hexinfluences" edge to the HexInfluence entity by IDs.
func (huo *HexUpdateOne) AddHexinfluenceIDs(ids ...int) *HexUpdateOne {
	huo.mutation.AddHexinfluenceIDs(ids...)
	return huo
}

// AddHexinfluences adds the "hexinfluences" edges to the HexInfluence entity.
func (huo *HexUpdateOne) AddHexinfluences(h ...*HexInfluence) *HexUpdateOne {
	ids := make([]int, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return huo.AddHexinfluenceIDs(ids...)
}

// AddHexleaderboardIDs adds the "hexleaderboards" edge to the HexLeaderboard entity by IDs.
func (huo *HexUpdateOne) AddHexleaderboardIDs(ids ...int) *HexUpdateOne {
	huo.mutation.AddHexleaderboardIDs(ids...)
	return huo
}

// AddHexleaderboards adds the "hexleaderboards" edges to the HexLeaderboard entity.
func (huo *HexUpdateOne) AddHexleaderboards(h ...*HexLeaderboard) *HexUpdateOne {
	ids := make([]int, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return huo.AddHexleaderboardIDs(ids...)
}

// Mutation returns the HexMutation object of the builder.
func (huo *HexUpdateOne) Mutation() *HexMutation {
	return huo.mutation
}

// ClearHexinfluences clears all "hexinfluences" edges to the HexInfluence entity.
func (huo *HexUpdateOne) ClearHexinfluences() *HexUpdateOne {
	huo.mutation.ClearHexinfluences()
	return huo
}

// RemoveHexinfluenceIDs removes the "hexinfluences" edge to HexInfluence entities by IDs.
func (huo *HexUpdateOne) RemoveHexinfluenceIDs(ids ...int) *HexUpdateOne {
	huo.mutation.RemoveHexinfluenceIDs(ids...)
	return huo
}

// RemoveHexinfluences removes "hexinfluences" edges to HexInfluence entities.
func (huo *HexUpdateOne) RemoveHexinfluences(h ...*HexInfluence) *HexUpdateOne {
	ids := make([]int, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return huo.RemoveHexinfluenceIDs(ids...)
}

// ClearHexleaderboards clears all "hexleaderboards" edges to the HexLeaderboard entity.
func (huo *HexUpdateOne) ClearHexleaderboards() *HexUpdateOne {
	huo.mutation.ClearHexleaderboards()
	return huo
}

// RemoveHexleaderboardIDs removes the "hexleaderboards" edge to HexLeaderboard entities by IDs.
func (huo *HexUpdateOne) RemoveHexleaderboardIDs(ids ...int) *HexUpdateOne {
	huo.mutation.RemoveHexleaderboardIDs(ids...)
	return huo
}

// RemoveHexleaderboards removes "hexleaderboards" edges to HexLeaderboard entities.
func (huo *HexUpdateOne) RemoveHexleaderboards(h ...*HexLeaderboard) *HexUpdateOne {
	ids := make([]int, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return huo.RemoveHexleaderboardIDs(ids...)
}

// Where appends a list predicates to the HexUpdate builder.
func (huo *HexUpdateOne) Where(ps ...predicate.Hex) *HexUpdateOne {
	huo.mutation.Where(ps...)
	return huo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (huo *HexUpdateOne) Select(field string, fields ...string) *HexUpdateOne {
	huo.fields = append([]string{field}, fields...)
	return huo
}

// Save executes the query and returns the updated Hex entity.
func (huo *HexUpdateOne) Save(ctx context.Context) (*Hex, error) {
	return withHooks(ctx, huo.sqlSave, huo.mutation, huo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (huo *HexUpdateOne) SaveX(ctx context.Context) *Hex {
	node, err := huo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (huo *HexUpdateOne) Exec(ctx context.Context) error {
	_, err := huo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (huo *HexUpdateOne) ExecX(ctx context.Context) {
	if err := huo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (huo *HexUpdateOne) sqlSave(ctx context.Context) (_node *Hex, err error) {
	_spec := sqlgraph.NewUpdateSpec(hex.Table, hex.Columns, sqlgraph.NewFieldSpec(hex.FieldID, field.TypeString))
	id, ok := huo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Hex.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := huo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hex.FieldID)
		for _, f := range fields {
			if !hex.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hex.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := huo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if huo.mutation.HexinfluencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hex.HexinfluencesTable,
			Columns: []string{hex.HexinfluencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hexinfluence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := huo.mutation.RemovedHexinfluencesIDs(); len(nodes) > 0 && !huo.mutation.HexinfluencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hex.HexinfluencesTable,
			Columns: []string{hex.HexinfluencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hexinfluence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := huo.mutation.HexinfluencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hex.HexinfluencesTable,
			Columns: []string{hex.HexinfluencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hexinfluence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if huo.mutation.HexleaderboardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hex.HexleaderboardsTable,
			Columns: []string{hex.HexleaderboardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hexleaderboard.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := huo.mutation.RemovedHexleaderboardsIDs(); len(nodes) > 0 && !huo.mutation.HexleaderboardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hex.HexleaderboardsTable,
			Columns: []string{hex.HexleaderboardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hexleaderboard.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := huo.mutation.HexleaderboardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hex.HexleaderboardsTable,
			Columns: []string{hex.HexleaderboardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hexleaderboard.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Hex{config: huo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, huo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hex.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	huo.mutation.done = true
	return _node, nil
}
