// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"stride-wars-app/ent/hex"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HexCreate is the builder for creating a Hex entity.
type HexCreate struct {
	config
	mutation *HexMutation
	hooks    []Hook
}

// SetHexOwner sets the "hex_owner" field.
func (hc *HexCreate) SetHexOwner(i int64) *HexCreate {
	hc.mutation.SetHexOwner(i)
	return hc
}

// SetCreatedAt sets the "created_at" field.
func (hc *HexCreate) SetCreatedAt(t time.Time) *HexCreate {
	hc.mutation.SetCreatedAt(t)
	return hc
}

// SetUpdatedAt sets the "updated_at" field.
func (hc *HexCreate) SetUpdatedAt(t time.Time) *HexCreate {
	hc.mutation.SetUpdatedAt(t)
	return hc
}

// SetIsActive sets the "is_active" field.
func (hc *HexCreate) SetIsActive(b bool) *HexCreate {
	hc.mutation.SetIsActive(b)
	return hc
}

// Mutation returns the HexMutation object of the builder.
func (hc *HexCreate) Mutation() *HexMutation {
	return hc.mutation
}

// Save creates the Hex in the database.
func (hc *HexCreate) Save(ctx context.Context) (*Hex, error) {
	return withHooks(ctx, hc.sqlSave, hc.mutation, hc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (hc *HexCreate) SaveX(ctx context.Context) *Hex {
	v, err := hc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hc *HexCreate) Exec(ctx context.Context) error {
	_, err := hc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hc *HexCreate) ExecX(ctx context.Context) {
	if err := hc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hc *HexCreate) check() error {
	if _, ok := hc.mutation.HexOwner(); !ok {
		return &ValidationError{Name: "hex_owner", err: errors.New(`ent: missing required field "Hex.hex_owner"`)}
	}
	if _, ok := hc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Hex.created_at"`)}
	}
	if _, ok := hc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Hex.updated_at"`)}
	}
	if _, ok := hc.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Hex.is_active"`)}
	}
	return nil
}

func (hc *HexCreate) sqlSave(ctx context.Context) (*Hex, error) {
	if err := hc.check(); err != nil {
		return nil, err
	}
	_node, _spec := hc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	hc.mutation.id = &_node.ID
	hc.mutation.done = true
	return _node, nil
}

func (hc *HexCreate) createSpec() (*Hex, *sqlgraph.CreateSpec) {
	var (
		_node = &Hex{config: hc.config}
		_spec = sqlgraph.NewCreateSpec(hex.Table, sqlgraph.NewFieldSpec(hex.FieldID, field.TypeInt))
	)
	if value, ok := hc.mutation.HexOwner(); ok {
		_spec.SetField(hex.FieldHexOwner, field.TypeInt64, value)
		_node.HexOwner = value
	}
	if value, ok := hc.mutation.CreatedAt(); ok {
		_spec.SetField(hex.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := hc.mutation.UpdatedAt(); ok {
		_spec.SetField(hex.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := hc.mutation.IsActive(); ok {
		_spec.SetField(hex.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	return _node, _spec
}

// HexCreateBulk is the builder for creating many Hex entities in bulk.
type HexCreateBulk struct {
	config
	err      error
	builders []*HexCreate
}

// Save creates the Hex entities in the database.
func (hcb *HexCreateBulk) Save(ctx context.Context) ([]*Hex, error) {
	if hcb.err != nil {
		return nil, hcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(hcb.builders))
	nodes := make([]*Hex, len(hcb.builders))
	mutators := make([]Mutator, len(hcb.builders))
	for i := range hcb.builders {
		func(i int, root context.Context) {
			builder := hcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HexMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hcb *HexCreateBulk) SaveX(ctx context.Context) []*Hex {
	v, err := hcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hcb *HexCreateBulk) Exec(ctx context.Context) error {
	_, err := hcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hcb *HexCreateBulk) ExecX(ctx context.Context) {
	if err := hcb.Exec(ctx); err != nil {
		panic(err)
	}
}
