// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"stride-wars-app/ent/hex"
	"stride-wars-app/ent/hexinfluence"
	"stride-wars-app/ent/hexleaderboard"
	"stride-wars-app/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HexQuery is the builder for querying Hex entities.
type HexQuery struct {
	config
	ctx                 *QueryContext
	order               []hex.OrderOption
	inters              []Interceptor
	predicates          []predicate.Hex
	withHexinfluences   *HexInfluenceQuery
	withHexleaderboards *HexLeaderboardQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HexQuery builder.
func (hq *HexQuery) Where(ps ...predicate.Hex) *HexQuery {
	hq.predicates = append(hq.predicates, ps...)
	return hq
}

// Limit the number of records to be returned by this query.
func (hq *HexQuery) Limit(limit int) *HexQuery {
	hq.ctx.Limit = &limit
	return hq
}

// Offset to start from.
func (hq *HexQuery) Offset(offset int) *HexQuery {
	hq.ctx.Offset = &offset
	return hq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (hq *HexQuery) Unique(unique bool) *HexQuery {
	hq.ctx.Unique = &unique
	return hq
}

// Order specifies how the records should be ordered.
func (hq *HexQuery) Order(o ...hex.OrderOption) *HexQuery {
	hq.order = append(hq.order, o...)
	return hq
}

// QueryHexinfluences chains the current query on the "hexinfluences" edge.
func (hq *HexQuery) QueryHexinfluences() *HexInfluenceQuery {
	query := (&HexInfluenceClient{config: hq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hex.Table, hex.FieldID, selector),
			sqlgraph.To(hexinfluence.Table, hexinfluence.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, hex.HexinfluencesTable, hex.HexinfluencesColumn),
		)
		fromU = sqlgraph.SetNeighbors(hq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryHexleaderboards chains the current query on the "hexleaderboards" edge.
func (hq *HexQuery) QueryHexleaderboards() *HexLeaderboardQuery {
	query := (&HexLeaderboardClient{config: hq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hex.Table, hex.FieldID, selector),
			sqlgraph.To(hexleaderboard.Table, hexleaderboard.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, hex.HexleaderboardsTable, hex.HexleaderboardsColumn),
		)
		fromU = sqlgraph.SetNeighbors(hq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Hex entity from the query.
// Returns a *NotFoundError when no Hex was found.
func (hq *HexQuery) First(ctx context.Context) (*Hex, error) {
	nodes, err := hq.Limit(1).All(setContextOp(ctx, hq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{hex.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (hq *HexQuery) FirstX(ctx context.Context) *Hex {
	node, err := hq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Hex ID from the query.
// Returns a *NotFoundError when no Hex ID was found.
func (hq *HexQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = hq.Limit(1).IDs(setContextOp(ctx, hq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{hex.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (hq *HexQuery) FirstIDX(ctx context.Context) string {
	id, err := hq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Hex entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Hex entity is found.
// Returns a *NotFoundError when no Hex entities are found.
func (hq *HexQuery) Only(ctx context.Context) (*Hex, error) {
	nodes, err := hq.Limit(2).All(setContextOp(ctx, hq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{hex.Label}
	default:
		return nil, &NotSingularError{hex.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (hq *HexQuery) OnlyX(ctx context.Context) *Hex {
	node, err := hq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Hex ID in the query.
// Returns a *NotSingularError when more than one Hex ID is found.
// Returns a *NotFoundError when no entities are found.
func (hq *HexQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = hq.Limit(2).IDs(setContextOp(ctx, hq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{hex.Label}
	default:
		err = &NotSingularError{hex.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (hq *HexQuery) OnlyIDX(ctx context.Context) string {
	id, err := hq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Hexes.
func (hq *HexQuery) All(ctx context.Context) ([]*Hex, error) {
	ctx = setContextOp(ctx, hq.ctx, ent.OpQueryAll)
	if err := hq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Hex, *HexQuery]()
	return withInterceptors[[]*Hex](ctx, hq, qr, hq.inters)
}

// AllX is like All, but panics if an error occurs.
func (hq *HexQuery) AllX(ctx context.Context) []*Hex {
	nodes, err := hq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Hex IDs.
func (hq *HexQuery) IDs(ctx context.Context) (ids []string, err error) {
	if hq.ctx.Unique == nil && hq.path != nil {
		hq.Unique(true)
	}
	ctx = setContextOp(ctx, hq.ctx, ent.OpQueryIDs)
	if err = hq.Select(hex.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (hq *HexQuery) IDsX(ctx context.Context) []string {
	ids, err := hq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (hq *HexQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, hq.ctx, ent.OpQueryCount)
	if err := hq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, hq, querierCount[*HexQuery](), hq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (hq *HexQuery) CountX(ctx context.Context) int {
	count, err := hq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (hq *HexQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, hq.ctx, ent.OpQueryExist)
	switch _, err := hq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (hq *HexQuery) ExistX(ctx context.Context) bool {
	exist, err := hq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HexQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (hq *HexQuery) Clone() *HexQuery {
	if hq == nil {
		return nil
	}
	return &HexQuery{
		config:              hq.config,
		ctx:                 hq.ctx.Clone(),
		order:               append([]hex.OrderOption{}, hq.order...),
		inters:              append([]Interceptor{}, hq.inters...),
		predicates:          append([]predicate.Hex{}, hq.predicates...),
		withHexinfluences:   hq.withHexinfluences.Clone(),
		withHexleaderboards: hq.withHexleaderboards.Clone(),
		// clone intermediate query.
		sql:  hq.sql.Clone(),
		path: hq.path,
	}
}

// WithHexinfluences tells the query-builder to eager-load the nodes that are connected to
// the "hexinfluences" edge. The optional arguments are used to configure the query builder of the edge.
func (hq *HexQuery) WithHexinfluences(opts ...func(*HexInfluenceQuery)) *HexQuery {
	query := (&HexInfluenceClient{config: hq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	hq.withHexinfluences = query
	return hq
}

// WithHexleaderboards tells the query-builder to eager-load the nodes that are connected to
// the "hexleaderboards" edge. The optional arguments are used to configure the query builder of the edge.
func (hq *HexQuery) WithHexleaderboards(opts ...func(*HexLeaderboardQuery)) *HexQuery {
	query := (&HexLeaderboardClient{config: hq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	hq.withHexleaderboards = query
	return hq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (hq *HexQuery) GroupBy(field string, fields ...string) *HexGroupBy {
	hq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HexGroupBy{build: hq}
	grbuild.flds = &hq.ctx.Fields
	grbuild.label = hex.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (hq *HexQuery) Select(fields ...string) *HexSelect {
	hq.ctx.Fields = append(hq.ctx.Fields, fields...)
	sbuild := &HexSelect{HexQuery: hq}
	sbuild.label = hex.Label
	sbuild.flds, sbuild.scan = &hq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HexSelect configured with the given aggregations.
func (hq *HexQuery) Aggregate(fns ...AggregateFunc) *HexSelect {
	return hq.Select().Aggregate(fns...)
}

func (hq *HexQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range hq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, hq); err != nil {
				return err
			}
		}
	}
	for _, f := range hq.ctx.Fields {
		if !hex.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if hq.path != nil {
		prev, err := hq.path(ctx)
		if err != nil {
			return err
		}
		hq.sql = prev
	}
	return nil
}

func (hq *HexQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Hex, error) {
	var (
		nodes       = []*Hex{}
		_spec       = hq.querySpec()
		loadedTypes = [2]bool{
			hq.withHexinfluences != nil,
			hq.withHexleaderboards != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Hex).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Hex{config: hq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, hq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := hq.withHexinfluences; query != nil {
		if err := hq.loadHexinfluences(ctx, query, nodes,
			func(n *Hex) { n.Edges.Hexinfluences = []*HexInfluence{} },
			func(n *Hex, e *HexInfluence) { n.Edges.Hexinfluences = append(n.Edges.Hexinfluences, e) }); err != nil {
			return nil, err
		}
	}
	if query := hq.withHexleaderboards; query != nil {
		if err := hq.loadHexleaderboards(ctx, query, nodes,
			func(n *Hex) { n.Edges.Hexleaderboards = []*HexLeaderboard{} },
			func(n *Hex, e *HexLeaderboard) { n.Edges.Hexleaderboards = append(n.Edges.Hexleaderboards, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (hq *HexQuery) loadHexinfluences(ctx context.Context, query *HexInfluenceQuery, nodes []*Hex, init func(*Hex), assign func(*Hex, *HexInfluence)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Hex)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(hexinfluence.FieldH3Index)
	}
	query.Where(predicate.HexInfluence(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(hex.HexinfluencesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.H3Index
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "h3_index" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (hq *HexQuery) loadHexleaderboards(ctx context.Context, query *HexLeaderboardQuery, nodes []*Hex, init func(*Hex), assign func(*Hex, *HexLeaderboard)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Hex)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(hexleaderboard.FieldH3Index)
	}
	query.Where(predicate.HexLeaderboard(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(hex.HexleaderboardsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.H3Index
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "h3_index" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (hq *HexQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := hq.querySpec()
	_spec.Node.Columns = hq.ctx.Fields
	if len(hq.ctx.Fields) > 0 {
		_spec.Unique = hq.ctx.Unique != nil && *hq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, hq.driver, _spec)
}

func (hq *HexQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(hex.Table, hex.Columns, sqlgraph.NewFieldSpec(hex.FieldID, field.TypeString))
	_spec.From = hq.sql
	if unique := hq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if hq.path != nil {
		_spec.Unique = true
	}
	if fields := hq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hex.FieldID)
		for i := range fields {
			if fields[i] != hex.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := hq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := hq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := hq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := hq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (hq *HexQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(hq.driver.Dialect())
	t1 := builder.Table(hex.Table)
	columns := hq.ctx.Fields
	if len(columns) == 0 {
		columns = hex.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if hq.sql != nil {
		selector = hq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if hq.ctx.Unique != nil && *hq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range hq.predicates {
		p(selector)
	}
	for _, p := range hq.order {
		p(selector)
	}
	if offset := hq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := hq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HexGroupBy is the group-by builder for Hex entities.
type HexGroupBy struct {
	selector
	build *HexQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hgb *HexGroupBy) Aggregate(fns ...AggregateFunc) *HexGroupBy {
	hgb.fns = append(hgb.fns, fns...)
	return hgb
}

// Scan applies the selector query and scans the result into the given value.
func (hgb *HexGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hgb.build.ctx, ent.OpQueryGroupBy)
	if err := hgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HexQuery, *HexGroupBy](ctx, hgb.build, hgb, hgb.build.inters, v)
}

func (hgb *HexGroupBy) sqlScan(ctx context.Context, root *HexQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(hgb.fns))
	for _, fn := range hgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*hgb.flds)+len(hgb.fns))
		for _, f := range *hgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*hgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HexSelect is the builder for selecting fields of Hex entities.
type HexSelect struct {
	*HexQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (hs *HexSelect) Aggregate(fns ...AggregateFunc) *HexSelect {
	hs.fns = append(hs.fns, fns...)
	return hs
}

// Scan applies the selector query and scans the result into the given value.
func (hs *HexSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hs.ctx, ent.OpQuerySelect)
	if err := hs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HexQuery, *HexSelect](ctx, hs.HexQuery, hs, hs.inters, v)
}

func (hs *HexSelect) sqlScan(ctx context.Context, root *HexQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(hs.fns))
	for _, fn := range hs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*hs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
