// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"stride-wars-app/ent/hex"
	"stride-wars-app/ent/hexinfluence"
	"stride-wars-app/ent/hexleaderboard"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HexCreate is the builder for creating a Hex entity.
type HexCreate struct {
	config
	mutation *HexMutation
	hooks    []Hook
}

// SetID sets the "id" field.
func (hc *HexCreate) SetID(s string) *HexCreate {
	hc.mutation.SetID(s)
	return hc
}

// AddHexinfluenceIDs adds the "hexinfluences" edge to the HexInfluence entity by IDs.
func (hc *HexCreate) AddHexinfluenceIDs(ids ...int) *HexCreate {
	hc.mutation.AddHexinfluenceIDs(ids...)
	return hc
}

// AddHexinfluences adds the "hexinfluences" edges to the HexInfluence entity.
func (hc *HexCreate) AddHexinfluences(h ...*HexInfluence) *HexCreate {
	ids := make([]int, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return hc.AddHexinfluenceIDs(ids...)
}

// AddHexleaderboardIDs adds the "hexleaderboards" edge to the HexLeaderboard entity by IDs.
func (hc *HexCreate) AddHexleaderboardIDs(ids ...int) *HexCreate {
	hc.mutation.AddHexleaderboardIDs(ids...)
	return hc
}

// AddHexleaderboards adds the "hexleaderboards" edges to the HexLeaderboard entity.
func (hc *HexCreate) AddHexleaderboards(h ...*HexLeaderboard) *HexCreate {
	ids := make([]int, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return hc.AddHexleaderboardIDs(ids...)
}

// Mutation returns the HexMutation object of the builder.
func (hc *HexCreate) Mutation() *HexMutation {
	return hc.mutation
}

// Save creates the Hex in the database.
func (hc *HexCreate) Save(ctx context.Context) (*Hex, error) {
	return withHooks(ctx, hc.sqlSave, hc.mutation, hc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (hc *HexCreate) SaveX(ctx context.Context) *Hex {
	v, err := hc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hc *HexCreate) Exec(ctx context.Context) error {
	_, err := hc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hc *HexCreate) ExecX(ctx context.Context) {
	if err := hc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hc *HexCreate) check() error {
	return nil
}

func (hc *HexCreate) sqlSave(ctx context.Context) (*Hex, error) {
	if err := hc.check(); err != nil {
		return nil, err
	}
	_node, _spec := hc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Hex.ID type: %T", _spec.ID.Value)
		}
	}
	hc.mutation.id = &_node.ID
	hc.mutation.done = true
	return _node, nil
}

func (hc *HexCreate) createSpec() (*Hex, *sqlgraph.CreateSpec) {
	var (
		_node = &Hex{config: hc.config}
		_spec = sqlgraph.NewCreateSpec(hex.Table, sqlgraph.NewFieldSpec(hex.FieldID, field.TypeString))
	)
	if id, ok := hc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if nodes := hc.mutation.HexinfluencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hex.HexinfluencesTable,
			Columns: []string{hex.HexinfluencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hexinfluence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := hc.mutation.HexleaderboardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   hex.HexleaderboardsTable,
			Columns: []string{hex.HexleaderboardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hexleaderboard.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HexCreateBulk is the builder for creating many Hex entities in bulk.
type HexCreateBulk struct {
	config
	err      error
	builders []*HexCreate
}

// Save creates the Hex entities in the database.
func (hcb *HexCreateBulk) Save(ctx context.Context) ([]*Hex, error) {
	if hcb.err != nil {
		return nil, hcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(hcb.builders))
	nodes := make([]*Hex, len(hcb.builders))
	mutators := make([]Mutator, len(hcb.builders))
	for i := range hcb.builders {
		func(i int, root context.Context) {
			builder := hcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HexMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hcb *HexCreateBulk) SaveX(ctx context.Context) []*Hex {
	v, err := hcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hcb *HexCreateBulk) Exec(ctx context.Context) error {
	_, err := hcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hcb *HexCreateBulk) ExecX(ctx context.Context) {
	if err := hcb.Exec(ctx); err != nil {
		panic(err)
	}
}
