// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"stride-wars-app/ent/hex"
	"stride-wars-app/ent/hexleaderboard"
	"stride-wars-app/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HexLeaderboardQuery is the builder for querying HexLeaderboard entities.
type HexLeaderboardQuery struct {
	config
	ctx        *QueryContext
	order      []hexleaderboard.OrderOption
	inters     []Interceptor
	predicates []predicate.HexLeaderboard
	withHex    *HexQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HexLeaderboardQuery builder.
func (hlq *HexLeaderboardQuery) Where(ps ...predicate.HexLeaderboard) *HexLeaderboardQuery {
	hlq.predicates = append(hlq.predicates, ps...)
	return hlq
}

// Limit the number of records to be returned by this query.
func (hlq *HexLeaderboardQuery) Limit(limit int) *HexLeaderboardQuery {
	hlq.ctx.Limit = &limit
	return hlq
}

// Offset to start from.
func (hlq *HexLeaderboardQuery) Offset(offset int) *HexLeaderboardQuery {
	hlq.ctx.Offset = &offset
	return hlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (hlq *HexLeaderboardQuery) Unique(unique bool) *HexLeaderboardQuery {
	hlq.ctx.Unique = &unique
	return hlq
}

// Order specifies how the records should be ordered.
func (hlq *HexLeaderboardQuery) Order(o ...hexleaderboard.OrderOption) *HexLeaderboardQuery {
	hlq.order = append(hlq.order, o...)
	return hlq
}

// QueryHex chains the current query on the "hex" edge.
func (hlq *HexLeaderboardQuery) QueryHex() *HexQuery {
	query := (&HexClient{config: hlq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := hlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := hlq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(hexleaderboard.Table, hexleaderboard.FieldID, selector),
			sqlgraph.To(hex.Table, hex.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, hexleaderboard.HexTable, hexleaderboard.HexColumn),
		)
		fromU = sqlgraph.SetNeighbors(hlq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first HexLeaderboard entity from the query.
// Returns a *NotFoundError when no HexLeaderboard was found.
func (hlq *HexLeaderboardQuery) First(ctx context.Context) (*HexLeaderboard, error) {
	nodes, err := hlq.Limit(1).All(setContextOp(ctx, hlq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{hexleaderboard.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (hlq *HexLeaderboardQuery) FirstX(ctx context.Context) *HexLeaderboard {
	node, err := hlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HexLeaderboard ID from the query.
// Returns a *NotFoundError when no HexLeaderboard ID was found.
func (hlq *HexLeaderboardQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hlq.Limit(1).IDs(setContextOp(ctx, hlq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{hexleaderboard.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (hlq *HexLeaderboardQuery) FirstIDX(ctx context.Context) int {
	id, err := hlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HexLeaderboard entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one HexLeaderboard entity is found.
// Returns a *NotFoundError when no HexLeaderboard entities are found.
func (hlq *HexLeaderboardQuery) Only(ctx context.Context) (*HexLeaderboard, error) {
	nodes, err := hlq.Limit(2).All(setContextOp(ctx, hlq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{hexleaderboard.Label}
	default:
		return nil, &NotSingularError{hexleaderboard.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (hlq *HexLeaderboardQuery) OnlyX(ctx context.Context) *HexLeaderboard {
	node, err := hlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HexLeaderboard ID in the query.
// Returns a *NotSingularError when more than one HexLeaderboard ID is found.
// Returns a *NotFoundError when no entities are found.
func (hlq *HexLeaderboardQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = hlq.Limit(2).IDs(setContextOp(ctx, hlq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{hexleaderboard.Label}
	default:
		err = &NotSingularError{hexleaderboard.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (hlq *HexLeaderboardQuery) OnlyIDX(ctx context.Context) int {
	id, err := hlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HexLeaderboards.
func (hlq *HexLeaderboardQuery) All(ctx context.Context) ([]*HexLeaderboard, error) {
	ctx = setContextOp(ctx, hlq.ctx, ent.OpQueryAll)
	if err := hlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*HexLeaderboard, *HexLeaderboardQuery]()
	return withInterceptors[[]*HexLeaderboard](ctx, hlq, qr, hlq.inters)
}

// AllX is like All, but panics if an error occurs.
func (hlq *HexLeaderboardQuery) AllX(ctx context.Context) []*HexLeaderboard {
	nodes, err := hlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HexLeaderboard IDs.
func (hlq *HexLeaderboardQuery) IDs(ctx context.Context) (ids []int, err error) {
	if hlq.ctx.Unique == nil && hlq.path != nil {
		hlq.Unique(true)
	}
	ctx = setContextOp(ctx, hlq.ctx, ent.OpQueryIDs)
	if err = hlq.Select(hexleaderboard.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (hlq *HexLeaderboardQuery) IDsX(ctx context.Context) []int {
	ids, err := hlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (hlq *HexLeaderboardQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, hlq.ctx, ent.OpQueryCount)
	if err := hlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, hlq, querierCount[*HexLeaderboardQuery](), hlq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (hlq *HexLeaderboardQuery) CountX(ctx context.Context) int {
	count, err := hlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (hlq *HexLeaderboardQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, hlq.ctx, ent.OpQueryExist)
	switch _, err := hlq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (hlq *HexLeaderboardQuery) ExistX(ctx context.Context) bool {
	exist, err := hlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HexLeaderboardQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (hlq *HexLeaderboardQuery) Clone() *HexLeaderboardQuery {
	if hlq == nil {
		return nil
	}
	return &HexLeaderboardQuery{
		config:     hlq.config,
		ctx:        hlq.ctx.Clone(),
		order:      append([]hexleaderboard.OrderOption{}, hlq.order...),
		inters:     append([]Interceptor{}, hlq.inters...),
		predicates: append([]predicate.HexLeaderboard{}, hlq.predicates...),
		withHex:    hlq.withHex.Clone(),
		// clone intermediate query.
		sql:  hlq.sql.Clone(),
		path: hlq.path,
	}
}

// WithHex tells the query-builder to eager-load the nodes that are connected to
// the "hex" edge. The optional arguments are used to configure the query builder of the edge.
func (hlq *HexLeaderboardQuery) WithHex(opts ...func(*HexQuery)) *HexLeaderboardQuery {
	query := (&HexClient{config: hlq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	hlq.withHex = query
	return hlq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		H3Index string `json:"h3_index,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HexLeaderboard.Query().
//		GroupBy(hexleaderboard.FieldH3Index).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (hlq *HexLeaderboardQuery) GroupBy(field string, fields ...string) *HexLeaderboardGroupBy {
	hlq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HexLeaderboardGroupBy{build: hlq}
	grbuild.flds = &hlq.ctx.Fields
	grbuild.label = hexleaderboard.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		H3Index string `json:"h3_index,omitempty"`
//	}
//
//	client.HexLeaderboard.Query().
//		Select(hexleaderboard.FieldH3Index).
//		Scan(ctx, &v)
func (hlq *HexLeaderboardQuery) Select(fields ...string) *HexLeaderboardSelect {
	hlq.ctx.Fields = append(hlq.ctx.Fields, fields...)
	sbuild := &HexLeaderboardSelect{HexLeaderboardQuery: hlq}
	sbuild.label = hexleaderboard.Label
	sbuild.flds, sbuild.scan = &hlq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HexLeaderboardSelect configured with the given aggregations.
func (hlq *HexLeaderboardQuery) Aggregate(fns ...AggregateFunc) *HexLeaderboardSelect {
	return hlq.Select().Aggregate(fns...)
}

func (hlq *HexLeaderboardQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range hlq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, hlq); err != nil {
				return err
			}
		}
	}
	for _, f := range hlq.ctx.Fields {
		if !hexleaderboard.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if hlq.path != nil {
		prev, err := hlq.path(ctx)
		if err != nil {
			return err
		}
		hlq.sql = prev
	}
	return nil
}

func (hlq *HexLeaderboardQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*HexLeaderboard, error) {
	var (
		nodes       = []*HexLeaderboard{}
		_spec       = hlq.querySpec()
		loadedTypes = [1]bool{
			hlq.withHex != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*HexLeaderboard).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &HexLeaderboard{config: hlq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, hlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := hlq.withHex; query != nil {
		if err := hlq.loadHex(ctx, query, nodes, nil,
			func(n *HexLeaderboard, e *Hex) { n.Edges.Hex = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (hlq *HexLeaderboardQuery) loadHex(ctx context.Context, query *HexQuery, nodes []*HexLeaderboard, init func(*HexLeaderboard), assign func(*HexLeaderboard, *Hex)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*HexLeaderboard)
	for i := range nodes {
		fk := nodes[i].H3Index
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(hex.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "h3_index" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (hlq *HexLeaderboardQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := hlq.querySpec()
	_spec.Node.Columns = hlq.ctx.Fields
	if len(hlq.ctx.Fields) > 0 {
		_spec.Unique = hlq.ctx.Unique != nil && *hlq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, hlq.driver, _spec)
}

func (hlq *HexLeaderboardQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(hexleaderboard.Table, hexleaderboard.Columns, sqlgraph.NewFieldSpec(hexleaderboard.FieldID, field.TypeInt))
	_spec.From = hlq.sql
	if unique := hlq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if hlq.path != nil {
		_spec.Unique = true
	}
	if fields := hlq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hexleaderboard.FieldID)
		for i := range fields {
			if fields[i] != hexleaderboard.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if hlq.withHex != nil {
			_spec.Node.AddColumnOnce(hexleaderboard.FieldH3Index)
		}
	}
	if ps := hlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := hlq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := hlq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := hlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (hlq *HexLeaderboardQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(hlq.driver.Dialect())
	t1 := builder.Table(hexleaderboard.Table)
	columns := hlq.ctx.Fields
	if len(columns) == 0 {
		columns = hexleaderboard.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if hlq.sql != nil {
		selector = hlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if hlq.ctx.Unique != nil && *hlq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range hlq.predicates {
		p(selector)
	}
	for _, p := range hlq.order {
		p(selector)
	}
	if offset := hlq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := hlq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HexLeaderboardGroupBy is the group-by builder for HexLeaderboard entities.
type HexLeaderboardGroupBy struct {
	selector
	build *HexLeaderboardQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hlgb *HexLeaderboardGroupBy) Aggregate(fns ...AggregateFunc) *HexLeaderboardGroupBy {
	hlgb.fns = append(hlgb.fns, fns...)
	return hlgb
}

// Scan applies the selector query and scans the result into the given value.
func (hlgb *HexLeaderboardGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hlgb.build.ctx, ent.OpQueryGroupBy)
	if err := hlgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HexLeaderboardQuery, *HexLeaderboardGroupBy](ctx, hlgb.build, hlgb, hlgb.build.inters, v)
}

func (hlgb *HexLeaderboardGroupBy) sqlScan(ctx context.Context, root *HexLeaderboardQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(hlgb.fns))
	for _, fn := range hlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*hlgb.flds)+len(hlgb.fns))
		for _, f := range *hlgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*hlgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hlgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HexLeaderboardSelect is the builder for selecting fields of HexLeaderboard entities.
type HexLeaderboardSelect struct {
	*HexLeaderboardQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (hls *HexLeaderboardSelect) Aggregate(fns ...AggregateFunc) *HexLeaderboardSelect {
	hls.fns = append(hls.fns, fns...)
	return hls
}

// Scan applies the selector query and scans the result into the given value.
func (hls *HexLeaderboardSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hls.ctx, ent.OpQuerySelect)
	if err := hls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HexLeaderboardQuery, *HexLeaderboardSelect](ctx, hls.HexLeaderboardQuery, hls, hls.inters, v)
}

func (hls *HexLeaderboardSelect) sqlScan(ctx context.Context, root *HexLeaderboardQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(hls.fns))
	for _, fn := range hls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*hls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
