// Code generated by ent, DO NOT EDIT.

package ent

import (
	"stride-wars-app/ent/activity"
	"stride-wars-app/ent/hexinfluence"
	"stride-wars-app/ent/hexleaderboard"
	"stride-wars-app/ent/model"
	"stride-wars-app/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	activityFields := model.Activity{}.Fields()
	_ = activityFields
	// activityDescCreatedAt is the schema descriptor for created_at field.
	activityDescCreatedAt := activityFields[5].Descriptor()
	// activity.DefaultCreatedAt holds the default value on creation for the created_at field.
	activity.DefaultCreatedAt = activityDescCreatedAt.Default.(time.Time)
	// activityDescID is the schema descriptor for id field.
	activityDescID := activityFields[0].Descriptor()
	// activity.DefaultID holds the default value on creation for the id field.
	activity.DefaultID = activityDescID.Default.(func() uuid.UUID)
	hexinfluenceFields := model.HexInfluence{}.Fields()
	_ = hexinfluenceFields
	// hexinfluenceDescID is the schema descriptor for id field.
	hexinfluenceDescID := hexinfluenceFields[0].Descriptor()
	// hexinfluence.DefaultID holds the default value on creation for the id field.
	hexinfluence.DefaultID = hexinfluenceDescID.Default.(func() uuid.UUID)
	hexleaderboardFields := model.HexLeaderboard{}.Fields()
	_ = hexleaderboardFields
	// hexleaderboardDescTopUsers is the schema descriptor for top_users field.
	hexleaderboardDescTopUsers := hexleaderboardFields[2].Descriptor()
	// hexleaderboard.DefaultTopUsers holds the default value on creation for the top_users field.
	hexleaderboard.DefaultTopUsers = hexleaderboardDescTopUsers.Default.([]model.TopUser)
	// hexleaderboardDescID is the schema descriptor for id field.
	hexleaderboardDescID := hexleaderboardFields[0].Descriptor()
	// hexleaderboard.DefaultID holds the default value on creation for the id field.
	hexleaderboard.DefaultID = hexleaderboardDescID.Default.(func() uuid.UUID)
	userFields := model.User{}.Fields()
	_ = userFields
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
