// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"stride-wars-app/ent/user"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ExternalUser holds the value of the "external_user" field.
	ExternalUser uuid.UUID `json:"external_user,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Activity holds the value of the activity edge.
	Activity []*Activity `json:"activity,omitempty"`
	// Friendship holds the value of the friendship edge.
	Friendship []*Friendship `json:"friendship,omitempty"`
	// Hexinfluence holds the value of the hexinfluence edge.
	Hexinfluence []*HexInfluence `json:"hexinfluence,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ActivityOrErr returns the Activity value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ActivityOrErr() ([]*Activity, error) {
	if e.loadedTypes[0] {
		return e.Activity, nil
	}
	return nil, &NotLoadedError{edge: "activity"}
}

// FriendshipOrErr returns the Friendship value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) FriendshipOrErr() ([]*Friendship, error) {
	if e.loadedTypes[1] {
		return e.Friendship, nil
	}
	return nil, &NotLoadedError{edge: "friendship"}
}

// HexinfluenceOrErr returns the Hexinfluence value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) HexinfluenceOrErr() ([]*HexInfluence, error) {
	if e.loadedTypes[2] {
		return e.Hexinfluence, nil
	}
	return nil, &NotLoadedError{edge: "hexinfluence"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldUsername:
			values[i] = new(sql.NullString)
		case user.FieldID, user.FieldExternalUser:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (u *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				u.ID = *value
			}
		case user.FieldExternalUser:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field external_user", values[i])
			} else if value != nil {
				u.ExternalUser = *value
			}
		case user.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				u.Username = value.String
			}
		default:
			u.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (u *User) Value(name string) (ent.Value, error) {
	return u.selectValues.Get(name)
}

// QueryActivity queries the "activity" edge of the User entity.
func (u *User) QueryActivity() *ActivityQuery {
	return NewUserClient(u.config).QueryActivity(u)
}

// QueryFriendship queries the "friendship" edge of the User entity.
func (u *User) QueryFriendship() *FriendshipQuery {
	return NewUserClient(u.config).QueryFriendship(u)
}

// QueryHexinfluence queries the "hexinfluence" edge of the User entity.
func (u *User) QueryHexinfluence() *HexInfluenceQuery {
	return NewUserClient(u.config).QueryHexinfluence(u)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *User) Update() *UserUpdateOne {
	return NewUserClient(u.config).UpdateOne(u)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (u *User) Unwrap() *User {
	_tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	u.config.driver = _tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", u.ID))
	builder.WriteString("external_user=")
	builder.WriteString(fmt.Sprintf("%v", u.ExternalUser))
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(u.Username)
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
