// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HexesColumns holds the columns for the "hexes" table.
	HexesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "hex_owner", Type: field.TypeInt64},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "is_active", Type: field.TypeBool},
	}
	// HexesTable holds the schema information for the "hexes" table.
	HexesTable = &schema.Table{
		Name:       "hexes",
		Columns:    HexesColumns,
		PrimaryKey: []*schema.Column{HexesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HexesTable,
	}
)

func init() {
}
