// Code generated by ent, DO NOT EDIT.

package hexinfluence

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the hexinfluence type in the database.
	Label = "hex_influence"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldH3Index holds the string denoting the h3_index field in the database.
	FieldH3Index = "h3_index"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldLastUpdated holds the string denoting the last_updated field in the database.
	FieldLastUpdated = "last_updated"
	// EdgeHex holds the string denoting the hex edge name in mutations.
	EdgeHex = "hex"
	// EdgeUsers holds the string denoting the users edge name in mutations.
	EdgeUsers = "users"
	// Table holds the table name of the hexinfluence in the database.
	Table = "hex_influences"
	// HexTable is the table that holds the hex relation/edge.
	HexTable = "hex_influences"
	// HexInverseTable is the table name for the Hex entity.
	// It exists in this package in order to avoid circular dependency with the "hex" package.
	HexInverseTable = "hexes"
	// HexColumn is the table column denoting the hex relation/edge.
	HexColumn = "h3_index"
	// UsersTable is the table that holds the users relation/edge.
	UsersTable = "hex_influences"
	// UsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UsersInverseTable = "users"
	// UsersColumn is the table column denoting the users relation/edge.
	UsersColumn = "user_id"
)

// Columns holds all SQL columns for hexinfluence fields.
var Columns = []string{
	FieldID,
	FieldH3Index,
	FieldUserID,
	FieldScore,
	FieldLastUpdated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the HexInfluence queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByH3Index orders the results by the h3_index field.
func ByH3Index(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldH3Index, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// ByLastUpdated orders the results by the last_updated field.
func ByLastUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUpdated, opts...).ToFunc()
}

// ByHexField orders the results by hex field.
func ByHexField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHexStep(), sql.OrderByField(field, opts...))
	}
}

// ByUsersField orders the results by users field.
func ByUsersField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsersStep(), sql.OrderByField(field, opts...))
	}
}
func newHexStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HexInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, HexTable, HexColumn),
	)
}
func newUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UsersTable, UsersColumn),
	)
}
