name: CI basic pipeline

on:
    push:
        branches: [main,frontend]
    pull_request:
        branches: [main]
jobs:
    frontend:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./frontend

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18
            
            - name: Install dependencies
              run: yarn install

            - name: Lint
              run: yarn run lint